name       : zstd
version    : 1.3.7
release    : 10
source     :
    - https://github.com/facebook/zstd/archive/v1.3.7.tar.gz : 5dd1e90eb16c25425880c8a91327f63de22891ffed082fcc17e5ae84fce0d5fb
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : system.utils
summary    : Zstd command line tools
description: |
    Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios.
clang      : yes
optimize   :
    - speed
setup      : |
    %patch -p1 < $pkgfiles/multi-thread-default.patch
build      : |
    %make
    %make manual
profile    : |
    %make check
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
