name       : zstd
version    : 1.4.2
release    : 14
source     :
    - https://github.com/facebook/zstd/releases/download/v1.4.2/zstd-1.4.2.tar.gz : 12730983b521f9a604c6789140fcb94fadf9a3ca99199765e33c56eb65b643c9
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : system.utils
summary    : Zstd command line tools
description: |
    Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios.
clang      : yes
emul32     : yes
optimize   :
    - speed
setup      : |
    %patch -p1 < $pkgfiles/multi-thread-default.patch
build      : |
    %make
    %make manual
    %make -C contrib/pzstd
profile    : |
    %make check
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
check      : |
    %make -C contrib/pzstd test
