name       : zstd
version    : 1.4.5
release    : 17
source     :
    - https://github.com/facebook/zstd/releases/download/v1.4.5/zstd-1.4.5.tar.gz : 98e91c7c6bf162bf90e4e70fdbc41a8188b9fa8de5ad840c401198014406ce9e
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
homepage   : https://facebook.github.io/zstd/
component  : system.utils
summary    : Zstd command line tools
description: |
    Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios.
clang      : yes
emul32     : yes
optimize   :
    - speed
setup      : |
    %patch -p1 < $pkgfiles/multi-thread-default.patch
build      : |
    %make
    %make manual
    %make -C contrib/pzstd
profile    : |
    %make check
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
    sed -i "s|/lib|/lib%LIBSUFFIX%|g" $installdir%libdir%/pkgconfig/libzstd.pc
check      : |
    %make -C contrib/pzstd test
