name       : zstd
version    : 1.4.0
release    : 12
source     :
    - https://github.com/facebook/zstd/releases/download/v1.4.0/zstd-1.4.0.tar.gz : 7f323f0e0c18488748f3d9b2d4353f00e904ea2ccd0372ea04d7f77aa1156557
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : system.utils
summary    : Zstd command line tools
description: |
    Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios.
clang      : yes
emul32     : yes
optimize   :
    - speed
setup      : |
    %patch -p1 < $pkgfiles/multi-thread-default.patch
build      : |
    %make
    %make manual
    %make -C contrib/pzstd
profile    : |
    %make check
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
check      : |
    %make -C contrib/pzstd test
