name       : zstd
version    : 1.4.8
release    : 18
source     :
    - https://github.com/facebook/zstd/releases/download/v1.4.8/zstd-1.4.8.tar.gz : 32478297ca1500211008d596276f5367c54198495cf677e9439f4791a4c69f24
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
homepage   : https://facebook.github.io/zstd/
component  : system.utils
summary    : Zstd command line tools
description: |
    Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios.
clang      : yes
emul32     : yes
optimize   :
    - speed
build      : |
    %make
    %make manual
    %make -C contrib/pzstd
profile    : |
    %make check
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
check      : |
    %make -C contrib/pzstd test
