name       : zstd
version    : 1.0.0
release    : 3
source     :
    - https://github.com/facebook/zstd/archive/v1.0.0.tar.gz : 197e6ef74da878cbf72844f38461bb18129d144fd5221b3598e973ecda6f5963
license    :
    - BSD-3-Clause
component  : system.utils
summary    : Zstd command line tools
description: |
    Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios.
build      : |
    %make
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
