name       : zstd
version    : 1.3.4
release    : 6
source     :
    - git|https://github.com/facebook/zstd.git : v1.3.4
license    :
    - BSD-3-Clause
    - GPL-2.0-only
component  : system.utils
summary    : Zstd command line tools
description: |
    Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios.
build      : |
    %make
    %make manual
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
check      : |
    %make check
