name       : zstd
version    : 1.3.5
release    : 9
source     :
    - https://github.com/facebook/zstd/archive/v1.3.5.tar.gz : d6e1559e4cdb7c4226767d4ddc990bff5f9aab77085ff0d0490c828b025e2eea
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : system.utils
summary    : Zstd command line tools
description: |
    Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios.
clang      : yes
optimize   :
    - speed
setup      : |
    %patch -p1 < $pkgfiles/zstd-l-stdin.patch
    %patch -p1 < $pkgfiles/multi-thread-default.patch
build      : |
    %make
    %make manual
profile    : |
    %make check
    %llvm_profile_merge
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
check      : |
    %make check
