name       : zstd
version    : 0.6.2
release    : 1
source     :
    - https://github.com/Cyan4973/zstd/archive/v0.6.2.tar.gz : f80c35b2860d66299c8457b891d05277ce4e88b9bdd1f10a431e74804404cb8f
license    :
        -  BSD-2-Clause
        -  GPL-2.0
component  : system.utils
summary    : Zstd command line tools
description: |
        Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios.
build      : |
    %make
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
