name       : zstd
version    : 1.4.9
release    : 19
source     :
    - https://github.com/facebook/zstd/releases/download/v1.4.9/zstd-1.4.9.tar.zst : 61dce0e9a5036d7fb9b5709ee6567c2c8a1b4ba48a8e43afe9ae355cc37bb494
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
homepage   : https://facebook.github.io/zstd/
component  : system.utils
summary    : Zstd command line tools
description: |
    Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios.
clang      : yes
emul32     : yes
optimize   :
    - speed
build      : |
    %make
    %make manual
    %make -C contrib/pzstd
profile    : |
    %make check
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
check      : |
    %make -C contrib/pzstd test
