name       : zstd
version    : 1.1.1
release    : 4
source     :
    - https://github.com/facebook/zstd/archive/v1.1.1.tar.gz : a92965a2480fecc6b7bf491106e93cbf69a298b865b6d623755b3a482d77e614
license    :
    - BSD-3-Clause
component  : system.utils
summary    : Zstd command line tools
description: |
    Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios.
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
