name       : zstd
version    : 1.2.0
release    : 5
source     :
    - https://github.com/facebook/zstd/archive/v1.2.0.tar.gz : 4a7e4593a3638276ca7f2a09dc4f38e674d8317bbea51626393ca73fc047cbfb
license    :
    - BSD-3-Clause
component  : system.utils
summary    : Zstd command line tools
description: |
    Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios.
build      : |
    %make
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
check      : |
    %make test
