name       : zstd
version    : 1.4.4
release    : 16
source     :
    - https://github.com/facebook/zstd/releases/download/v1.4.4/zstd-1.4.4.tar.gz : 59ef70ebb757ffe74a7b3fe9c305e2ba3350021a918d168a046c6300aeea9315
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : system.utils
summary    : Zstd command line tools
description: |
    Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level and better compression ratios.
clang      : yes
emul32     : yes
optimize   :
    - speed
setup      : |
    %patch -p1 < $pkgfiles/multi-thread-default.patch
build      : |
    %make
    %make manual
    %make -C contrib/pzstd
profile    : |
    %make check
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
    sed -i "s|/lib|/lib%LIBSUFFIX%|g" $installdir%libdir%/pkgconfig/libzstd.pc
check      : |
    %make -C contrib/pzstd test
